// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDateT")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            DueDateT = new DateTime(2024, 9, 27, 14, 2, 27, 69, DateTimeKind.Local).AddTicks(2035),
                            IsCompleted = false,
                            Priority = 2,
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            DueDateT = new DateTime(2024, 10, 1, 14, 2, 27, 69, DateTimeKind.Local).AddTicks(2096),
                            IsCompleted = false,
                            Priority = 1,
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            DueDateT = new DateTime(2024, 9, 29, 14, 2, 27, 69, DateTimeKind.Local).AddTicks(2098),
                            IsCompleted = false,
                            Priority = 3,
                            Title = "Task 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
